services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 2s
      retries: 20
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db-data: